TFS_USERNAME = ''
TFS_PASSWORD = ''
TFS_REPOSITORIES_URL = ''
TFS_REPOSITORY_ID = ''

SOURCE_DB_HOST = ''
SOURCE_DB_PORT = 0
SOURCE_DB_NAME = ''
SOURCE_DB_SCHEMA = ''

TARGET_DB_HOST = ''
TARGET_DB_PORT = 0
TARGET_DB_NAME = ''
TARGET_DB_SCHEMA = ''
